export const skills = [
  { name: 'JavaScript', icon: 'js' },
  { name: 'React js', icon: 'react' },
  { name: 'Next js', icon: 'next1' },
  { name: 'TypeScript', icon: 'ts' },
  { name: 'Redux Toolkit', icon: 'redux' },
  { name: 'React Query', icon: 'tanstak' },
  { name: 'Rest API', icon: 'rest' },
  { name: 'Apollo GraphQL', icon: 'apollo' },
  { name: 'Material UI', icon: 'material' },
  { name: 'styled components', icon: 'styled-components' },
  { name: 'Git', icon: 'git' },
  { name: 'HTML5', icon: 'html5' },
  { name: 'CSS3', icon: 'redux' },
  { name: 'SASS', icon: 'sass' },
  { name: 'WordPress', icon: 'wordpress' },
]
